io:
  data: ""
  output: ""
  n_bases: 120 # number of bases to truncate library to (if applicable)
  metadata: "map.csv"
  pep_fasta: "" 
 
samples:
  sample_1: ["s1_read_file_r1.fastq.gz","s1_read_file_r2.fastq.gz"]
  sample_1: ["s2_read_file_r1.fastq.gz","s2_read_file_r2.fastq.gz"]
